# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel #경계선찾는 기본커널

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[3, 2, 5, 1, 9, 1, 1, 9, 9, 5, 2, 5],
       [5, 2, 7, 1, 6, 1, 6, 7, 9, 8, 1, 1],
       [6, 9, 5, 5, 1, 1, 1, 3, 6, 1, 6, 7],
       [7, 8, 3, 6, 1, 6, 2, 1, 9, 5, 4, 7],
       [9, 0, 7, 5, 6, 8, 8, 6, 7, 9, 1, 8],
       [6, 1, 1, 7, 8, 0, 1, 0, 1, 7, 4, 2],
       [2, 2, 7, 8, 5, 9, 1, 5, 2, 3, 9, 3],
       [9, 6, 4, 9, 9, 0, 8, 3, 0, 1, 7, 9],
       [4, 6, 0, 3, 1, 7, 8, 5, 3, 1, 6, 6],
       [4, 0, 4, 5, 0, 4, 8, 6, 3, 9, 6, 1],
       [4, 4, 0, 7, 0, 3, 3, 6, 9, 8, 8, 0],
       [9, 6, 6, 3, 2, 2, 2, 6, 4, 8, 0, 6]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int)

In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[3, 2, 5, 1, 9, 1, 1, 9, 9, 5, 2, 5],
       [5, 2, 7, 1, 6, 1, 6, 7, 9, 8, 1, 1],
       [6, 9, 5, 5, 1, 1, 1, 3, 6, 1, 6, 7],
       [7, 8, 3, 6, 1, 6, 2, 1, 9, 5, 4, 7],
       [9, 0, 7, 5, 6, 8, 8, 6, 7, 9, 1, 8],
       [6, 1, 1, 7, 8, 0, 1, 0, 1, 7, 4, 2],
       [2, 2, 7, 8, 5, 9, 1, 5, 2, 3, 9, 3],
       [9, 6, 4, 9, 9, 0, 8, 3, 0, 1, 7, 9],
       [4, 6, 0, 3, 1, 7, 8, 5, 3, 1, 6, 6],
       [4, 0, 4, 5, 0, 4, 8, 6, 3, 9, 6, 1],
       [4, 4, 0, 7, 0, 3, 3, 6, 9, 8, 8, 0],
       [9, 6, 6, 3, 2, 2, 2, 6, 4, 8, 0, 6]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, -15,  15, -15,  12, -10,  14,   1,   6,  16, -13,   0],
       [  0,  15,  -4,   7,  -9,  -5,  -8,  -3,   2, -21,  11,   0],
       [  0,  13, -14,  10, -15,  12,  -8, -16,  17,  -3,  -3,   0],
       [  0, -25,  19,  -6,   2,  12,  15,   8,   3,  16, -21,   0],
       [  0,  -5, -18,   6,  14, -26,  -5, -13, -12,  11,  -3,   0],
       [  0,  -8,  13,   4, -14,  30, -19,  14,  -1,  -7,  19,   0],
       [  0,   3,  -6,  12,  21, -33,  20,  -6,  -9,  -7,   3,   0],
       [  0,  14, -17,  -3, -15,  15,   4,   0,   3, -15,   4,   0],
       [  0, -18,  11,   6, -10,  -2,  11,   2, -15,  18,   0,   0],
       [  0,   6, -21,  20, -12,   3,  -7,   0,  15,  -2,  18,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [13]:
img = cv2.imread('lena.png', 0)

In [14]:
h,w=img.shape

In [15]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [16]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [18]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()